In [1]:
import numpy as np

In [3]:
l=['sudh',1,2,3,4]

In [4]:
type(l)

list

In [5]:
np.array(l)

array(['sudh', '1', '2', '3', '4'], dtype='<U11')

In [6]:
type(np.array(l))

numpy.ndarray

In [14]:
a1=np.array([3,4,5,6,3.0])

In [10]:
a=np.array([[1,2],[3,4]])

In [11]:
a

array([[1, 2],
       [3, 4]])

In [13]:
a[1][1]

4

In [15]:
a1

array([3., 4., 5., 6., 3.])

In [16]:
a1[1]

4.0

In [20]:
a2=np.array([1,2,3,4],ndmin=4)

In [21]:
a2

array([[[[1, 2, 3, 4]]]])

In [24]:
a2[0][0][0][0]

1

In [25]:
a

array([[1, 2],
       [3, 4]])

In [26]:
a[1][0]

3

In [28]:
np.asarray([1,2,3,4])

array([1, 2, 3, 4])

In [29]:
np.asanyarray([1,2,3,4])

array([1, 2, 3, 4])

In [30]:
np.array([1,2,3,4])
# array can be 0 dimension

array([1, 2, 3, 4])

In [31]:
np.mat([1,2,3,4])
# it written 2 dimension by default

matrix([[1, 2, 3, 4]])

In [32]:
a=[1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [33]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [34]:
np.fromfunction(lambda i,j: i==j,(3,3))
# to generate matrix, we use fromfunction

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [35]:
np.fromfunction(lambda i,j:i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [36]:
np.fromfunction(lambda i,j:i*j,(4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [40]:
np.fromfunction(lambda i,j,z: i*j*z,(3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 1., 2.],
        [0., 2., 4.]],

       [[0., 0., 0.],
        [0., 2., 4.],
        [0., 4., 8.]]])

In [41]:
np.fromfunction(lambda i,j,z: i*j*z,(3,3,2),dtype=int)
# (3,3,2) meaning is 3 matrices of 3 rows and 2 column 

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [42]:
np.fromfunction(lambda i,j,z: i*j*z,(4,3,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [45]:
np.fromfunction(lambda i,j,z,p: i*j*z*p,(4,3,2,2),dtype=int)
# 2*2 matrix of 3 arrays of 4 combination

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [47]:
a=np.fromfunction(lambda i,j,z: i*j*z,(4,3,2),dtype=int)

In [48]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [49]:
a.ndim
# to check the dimension

3

In [50]:
a.size
# to check the no.of elements

24

In [51]:
a.shape

(4, 3, 2)

In [52]:
a.dtype

dtype('int32')

In [54]:
import pandas as pd
pd.DataFrame(a)
# we cannot create multi dimension in pandas,,, so we convert it into 2 dimension

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [56]:
a=np.fromfunction(lambda i,j:i*j,(4,3),dtype=int)

In [57]:
a

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

In [58]:
pd.DataFrame(a)

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [59]:
a=np.fromfunction(lambda i,j:i*j,(400,100),dtype=int)

In [60]:
a

array([[    0,     0,     0, ...,     0,     0,     0],
       [    0,     1,     2, ...,    97,    98,    99],
       [    0,     2,     4, ...,   194,   196,   198],
       ...,
       [    0,   397,   794, ..., 38509, 38906, 39303],
       [    0,   398,   796, ..., 38606, 39004, 39402],
       [    0,   399,   798, ..., 38703, 39102, 39501]])

In [61]:
pd.DataFrame(a)

0    1    2     3     4     5     6     7     8     9   ...     90  \
0     0    0    0     0     0     0     0     0     0     0  ...      0   
1     0    1    2     3     4     5     6     7     8     9  ...     90   
2     0    2    4     6     8    10    12    14    16    18  ...    180   
3     0    3    6     9    12    15    18    21    24    27  ...    270   
4     0    4    8    12    16    20    24    28    32    36  ...    360   
..   ..  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
395   0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  35550   
396   0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  35640   
397   0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  35730   
398   0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  35820   
399   0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  35910   

        91     92     93     94     95     96     97     98     99  
0        0      0      0      0      0      0      0      0      0  
1       91     92     93     94     95     96     97     98     99  
2      182    184    186    188    190    192    194    196    198  
3      273    276    279    282    285    288    291    294    297  
4      364    368    372    376    380    384    388    392    396  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
395  35945  36340  36735  37130  37525  37920  38315  38710  39105  
396  36036  36432  36828  37224  37620  38016  38412  38808  39204  
397  36127  36524  36921  37318  37715  38112  38509  38906  39303  
398  36218  36616  37014  37412  37810  38208  38606  39004  39402  
399  36309  36708  37107  37506  37905  38304  38703  39102  39501  

[400 rows x 100 columns]

In [62]:
np.random.rand(10,4)

array([[0.7798792 , 0.19597732, 0.00406338, 0.74619418],
       [0.23445309, 0.79556131, 0.27709527, 0.33919333],
       [0.46530178, 0.4410364 , 0.0901588 , 0.39953546],
       [0.4727442 , 0.20741237, 0.00757645, 0.58186554],
       [0.86185205, 0.02137496, 0.11907456, 0.96013651],
       [0.86220146, 0.70228211, 0.00148982, 0.55114687],
       [0.85849008, 0.30295146, 0.02959912, 0.1117448 ],
       [0.59439961, 0.58297203, 0.22039669, 0.8827993 ],
       [0.10536496, 0.25330098, 0.67905977, 0.31510273],
       [0.1194459 , 0.2703497 , 0.17403973, 0.29745039]])

In [67]:
np.random.randint(4,100)
# it will generate random num between 4 and 100

79

In [68]:
np.random.randn(4,5)

array([[-0.88868238, -0.09232893, -0.52908414, -1.55398239,  0.50954745],
       [-0.28755174,  0.72899544, -0.34017745,  0.31771491, -0.22924854],
       [-2.15625103,  0.66117491, -1.0260466 , -1.70216108,  0.6987675 ],
       [-1.32343642, -1.49859654,  0.29434983,  1.80579676,  0.24741794]])

In [70]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -2.070324  0.887710 -1.541059 -0.607455  0.022599
1  1.093548  0.004452 -0.960404  0.868711  1.558821
2 -0.355688  0.693382 -0.229937  1.276868  0.889243
3 -0.164271 -1.637503 -0.404434  0.681487 -1.764039

In [71]:
b=pd.DataFrame(np.random.randn(4,5))

In [72]:
b.ndim

2

In [75]:
a=np.fromfunction(lambda i,j,z: i*j*z,(4,3,2),dtype=int)

In [76]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [78]:
a.reshape(1,24)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 2, 0, 4, 0, 0, 0, 3,
        0, 6]])

In [79]:
a.reshape(3,8)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 2, 0, 0, 0, 2],
       [0, 4, 0, 0, 0, 3, 0, 6]])

In [81]:
a.reshape(6,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 0, 2],
       [0, 4, 0, 0],
       [0, 3, 0, 6]])

In [82]:
pd.DataFrame(a.reshape(6,4))

0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  1  0  2
3  0  0  0  2
4  0  4  0  0
5  0  3  0  6

In [83]:
a.reshape(4,2,1,3,1,1)

array([[[[[[0]],

          [[0]],

          [[0]]]],



        [[[[0]],

          [[0]],

          [[0]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[1]],

          [[0]],

          [[2]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[2]],

          [[0]],

          [[4]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[3]],

          [[0]],

          [[6]]]]]])

In [84]:
pd.DataFrame(a.reshape(4,2,1,3,1,1))

ValueError: Must pass 2-d input. shape=(4, 2, 1, 3, 1, 1)

In [85]:
a.reshape(4,-1)
# here by default -1 will read as 6

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [86]:
a.reshape(5,-1)

ValueError: cannot reshape array of size 24 into shape (5,newaxis)

In [87]:
a.reshape(2,-1)
# here -1 will read as 12

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [88]:
a.reshape(2,4,-265)
# here -265 will read as 3

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [89]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0  1.079620 -0.900337 -0.093929 -1.681972  1.487188
1 -0.731372 -0.605626  0.371015  0.825159 -2.176164
2  1.240359 -0.368136  1.103953 -1.159029 -1.084627
3  0.279633 -0.164701 -0.538843 -0.012497  2.062391

In [90]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [91]:
list(range(4,10,2))
# it will take a jump of two

[4, 6, 8]

In [92]:
list(range(4,10,0.2))
# we should give integer every time in normal range function

TypeError: 'float' object cannot be interpreted as an integer

In [96]:
a1=np.arange(4,10,0.5)
# in numpy we can give a floating values as a range

In [97]:
a1

array([4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [98]:
a1[1:4]

array([4.5, 5. , 5.5])

In [99]:
arr=np.random.rand(4,5)

In [100]:
arr

array([[0.93372133, 0.87941595, 0.16822117, 0.24515798, 0.26086227],
       [0.34245513, 0.45439456, 0.93859973, 0.77185307, 0.46911441],
       [0.00277869, 0.5316222 , 0.81242065, 0.41575131, 0.79585954],
       [0.89381709, 0.23574478, 0.70808341, 0.27911814, 0.06977096]])

In [101]:
# extract data which is >0.5
arr>0.5

array([[ True,  True, False, False, False],
       [False, False,  True,  True, False],
       [False,  True,  True, False,  True],
       [ True, False,  True, False, False]])

In [102]:
arr[arr>0.5]

array([0.93372133, 0.87941595, 0.93859973, 0.77185307, 0.5316222 ,
       0.81242065, 0.79585954, 0.89381709, 0.70808341])

In [103]:
arr[[1,2],[2]]
# extracting data which is intersectionh of 1 and 2 rows and 2 column

array([0.93859973, 0.81242065])

In [104]:
arr=np.random.rand(8,5)

In [105]:
arr

array([[0.98815016, 0.95007458, 0.66911467, 0.77671818, 0.46521295],
       [0.43639925, 0.94271472, 0.5451841 , 0.09725087, 0.15392106],
       [0.48147575, 0.93125218, 0.57444599, 0.30325779, 0.65311655],
       [0.57130566, 0.20393391, 0.04796954, 0.58762131, 0.6942223 ],
       [0.43123147, 0.35137357, 0.10506925, 0.24242395, 0.54878398],
       [0.2106325 , 0.59286602, 0.09033974, 0.24105378, 0.00966134],
       [0.46871852, 0.99056111, 0.75046624, 0.7053666 , 0.77439212],
       [0.78639899, 0.82117192, 0.89350699, 0.06472618, 0.33278249]])

In [107]:
arr[0:8,0:3]

array([[0.98815016, 0.95007458, 0.66911467],
       [0.43639925, 0.94271472, 0.5451841 ],
       [0.48147575, 0.93125218, 0.57444599],
       [0.57130566, 0.20393391, 0.04796954],
       [0.43123147, 0.35137357, 0.10506925],
       [0.2106325 , 0.59286602, 0.09033974],
       [0.46871852, 0.99056111, 0.75046624],
       [0.78639899, 0.82117192, 0.89350699]])

In [111]:
a2=arr[0:7,[0,1,2]]

In [112]:
a2

array([[0.98815016, 0.95007458, 0.66911467],
       [0.43639925, 0.94271472, 0.5451841 ],
       [0.48147575, 0.93125218, 0.57444599],
       [0.57130566, 0.20393391, 0.04796954],
       [0.43123147, 0.35137357, 0.10506925],
       [0.2106325 , 0.59286602, 0.09033974],
       [0.46871852, 0.99056111, 0.75046624]])

In [114]:
a2[0][0]=100

In [115]:
a2

array([[1.00000000e+02, 9.50074580e-01, 6.69114666e-01],
       [4.36399255e-01, 9.42714724e-01, 5.45184101e-01],
       [4.81475751e-01, 9.31252180e-01, 5.74445993e-01],
       [5.71305661e-01, 2.03933910e-01, 4.79695396e-02],
       [4.31231468e-01, 3.51373570e-01, 1.05069246e-01],
       [2.10632503e-01, 5.92866021e-01, 9.03397391e-02],
       [4.68718524e-01, 9.90561114e-01, 7.50466241e-01]])

In [121]:
a=np.array([[1,2],[3,4]])
b=np.array([[2,3],[4,5]])

In [122]:
a

array([[1, 2],
       [3, 4]])

In [123]:
b

array([[2, 3],
       [4, 5]])

In [124]:
a*b
# it will not give the matrix multiplication

array([[ 2,  6],
       [12, 20]])

In [125]:
m=a@b

In [126]:
m

array([[10, 13],
       [22, 29]])

In [127]:
m/0

<ipython-input-127-be1849f03ef3>:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])

In [1]:
import numpy as np

In [2]:
l=[2,3,4,5,6]

In [3]:
np.array(l)

array([2, 3, 4, 5, 6])

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((3,6),dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
5+np.ones((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [15]:
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [16]:
np.empty((4,5))
# it will generate random values... approx equal to zero

array([[8.99148142e-312, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000, 7.56569928e-307],
       [5.30276956e+180, 6.74640243e-067, 4.57576398e-071,
        4.26441358e-086, 3.35759155e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 2.85223391e-056],
       [3.57822422e-061, 2.56822628e+184, 9.05800028e-043,
        4.41299085e-143, 1.50008929e+248]])

In [20]:
np.empty((2,4,5))

array([[[6.95190032e-310, 6.95190032e-310, 6.95190032e-310,
         1.97626258e-323, 5.21733322e-321],
        [2.03060980e-321, 1.81816158e-321, 2.03060980e-321,
         5.27662110e-321, 2.03060980e-321],
        [4.52564132e-321, 2.03060980e-321, 1.66006057e-321,
         2.03060980e-321, 4.22920193e-321],
        [2.03060980e-321, 6.16593926e-321, 2.03060980e-321,
         3.45845952e-321, 2.03060980e-321]],

       [[6.16593926e-321, 1.97626258e-323, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000]]])

In [21]:
np.linspace(2,6)
# it will generate number from 2 to 6 of total of 50 numbers

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [22]:
np.linspace(2,6,10)
# it will generate 10 numbers from range of 2 to 6

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [24]:
np.linspace(2,6,10).reshape(5,2)

array([[2.        , 2.44444444],
       [2.88888889, 3.33333333],
       [3.77777778, 4.22222222],
       [4.66666667, 5.11111111],
       [5.55555556, 6.        ]])

In [25]:
np.linspace(2,6,10).reshape(2,5)

array([[2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778],
       [4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ]])

In [26]:
np.linspace(2,6,10,endpoint=False).reshape(5,2)
# if endpoint is False, then it will generate the numbers below 6

array([[2. , 2.4],
       [2.8, 3.2],
       [3.6, 4. ],
       [4.4, 4.8],
       [5.2, 5.6]])

In [28]:
np.linspace(2,6,10,endpoint=False,retstep=True)
# it will show the retstep of size 0.4

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [30]:
np.logspace(2,4,10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [33]:
a=np.arange(16).reshape(4,4)

In [34]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
a.max()
# it will give the maximum element

15

In [37]:
a1=np.arange(4,40).reshape(3,6,2)

In [40]:
a1

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [38]:
a1.max()

39

In [51]:
a1.max(axis=0)

array([[28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [52]:
a1.max(axis=1)

array([[14, 15],
       [26, 27],
       [38, 39]])

In [53]:
a1.max(axis=2)

array([[ 5,  7,  9, 11, 13, 15],
       [17, 19, 21, 23, 25, 27],
       [29, 31, 33, 35, 37, 39]])

In [46]:
a=np.arange(4,40).reshape(6,6)

In [47]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [48]:
a.max()
# return the value which is having the maximum value in the array

39

In [49]:
a.max(axis=0)
# return the maximum values comparing row wise

array([34, 35, 36, 37, 38, 39])

In [50]:
a.max(axis=1)
# return the maximum values comparing column wise

array([ 9, 15, 21, 27, 33, 39])

In [54]:
10+a
# it will add 10 to each element of a

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [55]:
a/0

<ipython-input-55-deacdc4ccabc>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [56]:
a**2
# it will give square of each value of a

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [57]:
pow(a,2)

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [58]:
pow(a,3)
# it will give cube of each value of a

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]], dtype=int32)

In [59]:
b=np.array([2,3,1,2,3,2])

In [62]:
b

array([2, 3, 1, 2, 3, 2])

In [61]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [60]:
a+b
# perform operation row wise

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [65]:
b1=b.T

In [66]:
a+b1

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [67]:
b=b.reshape(1,-1)

In [68]:
b

array([[2, 3, 1, 2, 3, 2]])

In [69]:
b.T

array([[2],
       [3],
       [1],
       [2],
       [3],
       [2]])

In [70]:
b.T+a
# perform operation row wise

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [36, 37, 38, 39, 40, 41]])

In [71]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [72]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [73]:
np.exp(a)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [74]:
np.log10(a)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

In [75]:
x=np.array([1,2,3])

In [76]:
y=x

In [77]:
y

array([1, 2, 3])

In [78]:
z=np.copy(x)

In [79]:
z

array([1, 2, 3])

In [80]:
x[0]=100

In [81]:
y

array([100,   2,   3])

In [82]:
z

array([1, 2, 3])

In [83]:
x

array([100,   2,   3])

In [85]:
id(z)

1820018031072

In [86]:
id(x)

1820023674480

In [87]:
id(y)

1820023674480

In [88]:
x

array([100,   2,   3])

In [89]:
id(x[0])

1820024044560

In [90]:
y

array([100,   2,   3])

In [91]:
id(y[0])

1820024044944

In [92]:
id(x[1])

1820024044880

In [93]:
id(y[1])

1820024045104

In [94]:
id(z[1])

1820024045232

In [95]:
x=np.array([1,2,3])

In [96]:
y=x

In [97]:
id(x)

1820025614624

In [98]:
id(y)

1820025614624

In [99]:
id(x[0])

1820024500400

In [100]:
id(y[0])

1820024500720

In [101]:
id(x[0])==id(y[0])

True